// Authoritative platform baseline data
export const initialSubmissions = [];

export const initialReviews = [
  {
    "id": 8,
    "insurer_id": "belairdirect",
    "created_at": "2026-08-10",
    "rating": 4.5,
    "title": "Great app, but renewal went up $35 for no reason",
    "body": "Signing up was super painless. Everything on the mobile app. But after 12 months with zero tickets or accidents, renewal notice arrived with a $35/mo hike. Had to call and negotiate down to $15.",
    "had_accident": 0,
    "claims_experience": "N/A",
    "payout_speed": "N/A",
    "author_city": "Markham",
    "vehicle": "2021 Toyota RAV4",
    "monthly_premium": 195,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 9,
    "insurer_id": "intact",
    "created_at": "2026-07-22",
    "rating": 5,
    "title": "Not-at-fault collision handled in 3 days",
    "body": "Someone backed into my passenger door in a plaza parking lot. Intact assigned an adjuster within 4 hours, authorized a rental via Enterprise immediately, and car was fixed at certified shop in 6 days. Worth the slightly higher premium.",
    "had_accident": 1,
    "claims_experience": "Prompt adjuster, rental car booked seamlessly, zero deductible hassle",
    "payout_speed": "3 days",
    "author_city": "Mississauga",
    "vehicle": "2022 Honda Civic",
    "monthly_premium": 260,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 10,
    "insurer_id": "caa",
    "created_at": "2026-09-01",
    "rating": 5,
    "title": "CAA MyPace is the ultimate hack if you work from home",
    "body": "I drive under 8,000 km per year because of remote work. I was paying $210 with TD, switched to CAA MyPace and now pay around $115/month based on actual mileage. Absolutely unbeatable.",
    "had_accident": 0,
    "claims_experience": "N/A",
    "payout_speed": "N/A",
    "author_city": "Toronto (Midtown)",
    "vehicle": "2019 Subaru Outback",
    "monthly_premium": 115,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 11,
    "insurer_id": "td",
    "created_at": "2026-06-18",
    "rating": 3,
    "title": "Good initial rate, but getting through to claims is a nightmare",
    "body": "Cheap rates if you graduated from UofT or Ryerson. But when windshield caught a rock on the 401, I was on hold for 85 minutes to file a glass claim. If you value customer service over price, look elsewhere.",
    "had_accident": 1,
    "claims_experience": "Long hold times, bureaucratic paperwork for glass replacement",
    "payout_speed": "14 days",
    "author_city": "Toronto (Downtown)",
    "vehicle": "2020 Mazda CX-5",
    "monthly_premium": 175,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 12,
    "insurer_id": "sonnet",
    "created_at": "2026-08-29",
    "rating": 3.5,
    "title": "100% digital quote was fast, but year 2 shock was real",
    "body": "Loved that I did not have to speak to a broker or sales rep. Got approved in 10 minutes online. Year 1 was $180/mo. Year 2 renewal came in at $245/mo with no changes on my record. Switched away immediately.",
    "had_accident": 0,
    "claims_experience": "N/A",
    "payout_speed": "N/A",
    "author_city": "Vaughan",
    "vehicle": "2023 Hyundai Elantra",
    "monthly_premium": 180,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 13,
    "insurer_id": "desjardins",
    "created_at": "2026-07-05",
    "rating": 4.5,
    "title": "Ajusto discount knocked off 18%",
    "body": "The Ajusto app is sensitive if you brake hard for yellow lights, but overall after 100 days my discount settled at 18%. Customer service reps are very polite and clear.",
    "had_accident": 0,
    "claims_experience": "N/A",
    "payout_speed": "N/A",
    "author_city": "Ottawa",
    "vehicle": "2021 Toyota Corolla",
    "monthly_premium": 140,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 14,
    "insurer_id": "intact",
    "created_at": "2026-08-14",
    "rating": 4,
    "title": "Brampton postal code hurts, but service is solid",
    "body": "L6Y postal code means you pay high regardless. Broker got me with Intact. Had an animal strike on country road, claim processed without any argument.",
    "had_accident": 1,
    "claims_experience": "Fair valuation, direct payment to body shop",
    "payout_speed": "5 days",
    "author_city": "Brampton",
    "vehicle": "2022 Ford F-150",
    "monthly_premium": 345,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 15,
    "insurer_id": "caa",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4.8,
    "title": "Best rate for low-mileage commuter",
    "body": "Switched to CAA MyPace because I work from home 3 days a week. Saved over $70/month compared to my previous policy. Renewal rate stayed identical.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Oakville",
    "vehicle": "2021 Toyota RAV4",
    "monthly_premium": 148,
    "rating_value": 5,
    "rating_claims": 5,
    "rating_support": 5,
    "rating_renewal": 5,
    "rating_ease": 4
  },
  {
    "id": 16,
    "insurer_id": "caa",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4.6,
    "title": "Smooth claim after parking lot scrape",
    "body": "Someone scraped my bumper at the grocery store. Called CAA, got rental car arranged same afternoon, and vehicle was fixed in 6 business days.",
    "had_accident": 1,
    "claims_experience": "Parking lot collision, not-at-fault claim",
    "payout_speed": "6 business days",
    "author_city": "Burlington",
    "vehicle": "2020 Subaru Forester",
    "monthly_premium": 165,
    "rating_value": 5,
    "rating_claims": 4,
    "rating_support": 5,
    "rating_renewal": 5,
    "rating_ease": 4
  },
  {
    "id": 17,
    "insurer_id": "intact",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4.2,
    "title": "Pricey but incredible claims service when needed",
    "body": "Intact is not the cheapest, but when I had a highway collision during snowstorm, their adjuster handled everything without hassle. Repair centre was top tier.",
    "had_accident": 1,
    "claims_experience": "Highway winter collision on 401",
    "payout_speed": "4 business days",
    "author_city": "Toronto (North York)",
    "vehicle": "2022 Honda CR-V",
    "monthly_premium": 245,
    "rating_value": 3,
    "rating_claims": 5,
    "rating_support": 5,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 18,
    "insurer_id": "td",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 3.8,
    "title": "Good alumni discount, but renewal crept up",
    "body": "Got a good rate initially with U of T alumni discount. Online portal is very convenient. However, second year renewal went up by $22/month despite zero tickets.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Mississauga",
    "vehicle": "2019 Mazda 3",
    "monthly_premium": 215,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 3,
    "rating_renewal": 3,
    "rating_ease": 5
  },
  {
    "id": 19,
    "insurer_id": "belairdirect",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4.2,
    "title": "Fast app setup, automerit discount works well",
    "body": "Was able to get insured in literally 10 minutes on my phone. The automerit app gave me an 18% discount after 6 months of smooth driving.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Ottawa",
    "vehicle": "2023 Hyundai Elantra",
    "monthly_premium": 185,
    "rating_value": 5,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 3,
    "rating_ease": 5
  },
  {
    "id": 20,
    "insurer_id": "desjardins",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4.4,
    "title": "Great rates in Ottawa region & bilingual service",
    "body": "Customer service agents are very friendly and clear. Ajusto app tracking is fair as long as you dont brake aggressively.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Ottawa (Kanata)",
    "vehicle": "2021 Volkswagen Golf",
    "monthly_premium": 172,
    "rating_value": 4,
    "rating_claims": 5,
    "rating_support": 5,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 21,
    "insurer_id": "sonnet",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4,
    "title": "Super easy to buy online with zero phone calls",
    "body": "Loved not having to talk to any sales reps. Everything in PDF right away. Changing deductible was 2 clicks.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Kitchener",
    "vehicle": "2018 Honda Civic",
    "monthly_premium": 205,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 3,
    "rating_ease": 5
  },
  {
    "id": 22,
    "insurer_id": "cooperators",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4.6,
    "title": "Local agent knows our family and keeps rates fair",
    "body": "We deal with the local Guelph office. When our daughter got her G2, they gave us practical advice on keeping premiums reasonable.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Guelph",
    "vehicle": "2020 Toyota Highlander",
    "monthly_premium": 228,
    "rating_value": 4,
    "rating_claims": 5,
    "rating_support": 5,
    "rating_renewal": 5,
    "rating_ease": 4
  },
  {
    "id": 23,
    "insurer_id": "squareone",
    "created_at": "2026-09-21T20:25:12.350Z",
    "rating": 4.6,
    "title": "Completely customized online quote in 5 minutes",
    "body": "Love being able to pick individual coverages and deductibles myself without pushy phone agents. Saved around $40/mo compared to my old renewal bill.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Toronto (North York)",
    "vehicle": "2023 Hyundai Elantra",
    "monthly_premium": 185,
    "rating_value": 5,
    "rating_claims": 4,
    "rating_support": 5,
    "rating_renewal": 4,
    "rating_ease": 5
  }
];

export const initialFeedback = [];

export const initialLeads = [];

export const initialStats = {
  "total_money_saved": 2700,
  "total_checks_run": 32,
  "avg_monthly_overpay": 0
};
