// Auto-generated snapshot of authoritative platform data
export const initialSubmissions = [
  {
    "id": 10,
    "created_at": "2026-09-12",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2022,
    "driver_age": 23,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 1,
    "provider_name": "Aviva",
    "monthly_premium": 440,
    "coverage_type": "Standard",
    "comment": "Insane price for young driver in Brampton"
  },
  {
    "id": 11,
    "created_at": "2026-09-11",
    "fsa": "L6Y",
    "city": "Brampton",
    "vehicle_make": "Lexus",
    "vehicle_model": "RX350",
    "vehicle_year": 2023,
    "driver_age": 42,
    "driver_profile": "experienced",
    "years_licensed": 18,
    "clean_record": 1,
    "provider_name": "Intact",
    "monthly_premium": 385,
    "coverage_type": "Comprehensive",
    "comment": "Theft tag mandatory, price jumped 30% from last year"
  },
  {
    "id": 12,
    "created_at": "2026-09-10",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Mazda",
    "vehicle_model": "CX-5",
    "vehicle_year": 2021,
    "driver_age": 34,
    "driver_profile": "experienced",
    "years_licensed": 12,
    "clean_record": 1,
    "provider_name": "Belairdirect",
    "monthly_premium": 195,
    "coverage_type": "Standard",
    "comment": "Underground condo parking discount applied"
  },
  {
    "id": 13,
    "created_at": "2026-09-09",
    "fsa": "K1P",
    "city": "Ottawa",
    "vehicle_make": "Subaru",
    "vehicle_model": "Outback",
    "vehicle_year": 2020,
    "driver_age": 39,
    "driver_profile": "experienced",
    "years_licensed": 16,
    "clean_record": 1,
    "provider_name": "CAA",
    "monthly_premium": 135,
    "coverage_type": "Standard",
    "comment": "Ottawa rates are so much better than GTA"
  },
  {
    "id": 15,
    "created_at": "2026-09-07",
    "fsa": "L4B",
    "city": "Richmond Hill",
    "vehicle_make": "Tesla",
    "vehicle_model": "Model 3",
    "vehicle_year": 2023,
    "driver_age": 36,
    "driver_profile": "experienced",
    "years_licensed": 14,
    "clean_record": 1,
    "provider_name": "Desjardins",
    "monthly_premium": 275,
    "coverage_type": "Comprehensive",
    "comment": "EV parts repair surcharge is noticeable"
  },
  {
    "id": 16,
    "created_at": "2026-09-05",
    "fsa": "M1B",
    "city": "Toronto (Scarborough)",
    "vehicle_make": "Hyundai",
    "vehicle_model": "Elantra",
    "vehicle_year": 2020,
    "driver_age": 26,
    "driver_profile": "young",
    "years_licensed": 5,
    "clean_record": 1,
    "provider_name": "Sonnet",
    "monthly_premium": 290,
    "coverage_type": "Standard",
    "comment": "Scarborough rate is almost as high as Brampton"
  },
  {
    "id": 17,
    "created_at": "2026-09-04",
    "fsa": "N2L",
    "city": "Waterloo",
    "vehicle_make": "Volkswagen",
    "vehicle_model": "Golf",
    "vehicle_year": 2019,
    "driver_age": 28,
    "driver_profile": "experienced",
    "years_licensed": 9,
    "clean_record": 1,
    "provider_name": "Onlia",
    "monthly_premium": 165,
    "coverage_type": "Standard",
    "comment": "Waterloo rate is decent, Onlia cash rewards work"
  },
  {
    "id": 18,
    "created_at": "2026-09-02",
    "fsa": "L8P",
    "city": "Hamilton",
    "vehicle_make": "Ford",
    "vehicle_model": "F-150",
    "vehicle_year": 2021,
    "driver_age": 48,
    "driver_profile": "experienced",
    "years_licensed": 25,
    "clean_record": 1,
    "provider_name": "Intact",
    "monthly_premium": 210,
    "coverage_type": "Standard",
    "comment": "Commercial / personal combo"
  },
  {
    "id": 20,
    "created_at": "2026-09-22",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2021,
    "driver_age": 24,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 0,
    "provider_name": "Belairdirect",
    "monthly_premium": 275,
    "coverage_type": "Full",
    "comment": "Test submission from INS-27 modal"
  },
  {
    "id": 21,
    "created_at": "2026-09-22",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Toyota",
    "vehicle_model": "RAV4",
    "vehicle_year": 2023,
    "driver_age": 45,
    "driver_profile": "experienced",
    "years_licensed": 20,
    "clean_record": 1,
    "provider_name": "TD Insurance",
    "monthly_premium": 220,
    "coverage_type": "Standard",
    "comment": "Submitted via Sanity Check"
  },
  {
    "id": 22,
    "created_at": "2026-09-22",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2021,
    "driver_age": 24,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 0,
    "provider_name": "Belairdirect",
    "monthly_premium": 275,
    "coverage_type": "Full",
    "comment": "Test submission from INS-27 modal"
  },
  {
    "id": 23,
    "created_at": "2026-09-22",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Toyota",
    "vehicle_model": "RAV4",
    "vehicle_year": 2023,
    "driver_age": 45,
    "driver_profile": "experienced",
    "years_licensed": 20,
    "clean_record": 1,
    "provider_name": "TD Insurance",
    "monthly_premium": 220,
    "coverage_type": "Standard",
    "comment": "Submitted via Sanity Check"
  },
  {
    "id": 24,
    "created_at": "2026-09-23",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2021,
    "driver_age": 24,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 0,
    "provider_name": "Belairdirect",
    "monthly_premium": 275,
    "coverage_type": "Full",
    "comment": "Test submission from INS-27 modal"
  },
  {
    "id": 25,
    "created_at": "2026-09-23",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Toyota",
    "vehicle_model": "RAV4",
    "vehicle_year": 2023,
    "driver_age": 45,
    "driver_profile": "experienced",
    "years_licensed": 20,
    "clean_record": 1,
    "provider_name": "TD Insurance",
    "monthly_premium": 220,
    "coverage_type": "Standard",
    "comment": "Submitted via Sanity Check"
  },
  {
    "id": 26,
    "created_at": "2026-09-23",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2021,
    "driver_age": 24,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 0,
    "provider_name": "Belairdirect",
    "monthly_premium": 275,
    "coverage_type": "Full",
    "comment": "Test submission from INS-27 modal"
  },
  {
    "id": 27,
    "created_at": "2026-09-23",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Toyota",
    "vehicle_model": "RAV4",
    "vehicle_year": 2023,
    "driver_age": 45,
    "driver_profile": "experienced",
    "years_licensed": 20,
    "clean_record": 1,
    "provider_name": "TD Insurance",
    "monthly_premium": 220,
    "coverage_type": "Standard",
    "comment": "Submitted via Sanity Check"
  },
  {
    "id": 28,
    "created_at": "2026-09-23",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2021,
    "driver_age": 24,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 0,
    "provider_name": "Belairdirect",
    "monthly_premium": 275,
    "coverage_type": "Full",
    "comment": "Test submission from INS-27 modal"
  },
  {
    "id": 29,
    "created_at": "2026-09-23",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Toyota",
    "vehicle_model": "RAV4",
    "vehicle_year": 2023,
    "driver_age": 45,
    "driver_profile": "experienced",
    "years_licensed": 20,
    "clean_record": 1,
    "provider_name": "TD Insurance",
    "monthly_premium": 220,
    "coverage_type": "Standard",
    "comment": "Submitted via Sanity Check"
  },
  {
    "id": 30,
    "created_at": "2026-09-24",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2021,
    "driver_age": 24,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 0,
    "provider_name": "Belairdirect",
    "monthly_premium": 275,
    "coverage_type": "Full",
    "comment": "Test submission from INS-27 modal"
  },
  {
    "id": 31,
    "created_at": "2026-09-24",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Toyota",
    "vehicle_model": "RAV4",
    "vehicle_year": 2023,
    "driver_age": 45,
    "driver_profile": "experienced",
    "years_licensed": 20,
    "clean_record": 1,
    "provider_name": "TD Insurance",
    "monthly_premium": 220,
    "coverage_type": "Standard",
    "comment": "Submitted via Sanity Check"
  },
  {
    "id": 32,
    "created_at": "2026-09-30",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2021,
    "driver_age": 24,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 0,
    "provider_name": "Belairdirect",
    "monthly_premium": 275,
    "coverage_type": "Full",
    "comment": "Test submission from INS-27 modal"
  },
  {
    "id": 33,
    "created_at": "2026-09-30",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Toyota",
    "vehicle_model": "RAV4",
    "vehicle_year": 2023,
    "driver_age": 45,
    "driver_profile": "experienced",
    "years_licensed": 20,
    "clean_record": 1,
    "provider_name": "TD Insurance",
    "monthly_premium": 220,
    "coverage_type": "Standard",
    "comment": "Submitted via Sanity Check"
  },
  {
    "id": 34,
    "created_at": "2026-09-30",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2021,
    "driver_age": 24,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 0,
    "provider_name": "Belairdirect",
    "monthly_premium": 275,
    "coverage_type": "Full",
    "comment": "Test submission from INS-27 modal"
  },
  {
    "id": 35,
    "created_at": "2026-09-30",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Toyota",
    "vehicle_model": "RAV4",
    "vehicle_year": 2023,
    "driver_age": 45,
    "driver_profile": "experienced",
    "years_licensed": 20,
    "clean_record": 1,
    "provider_name": "TD Insurance",
    "monthly_premium": 220,
    "coverage_type": "Standard",
    "comment": "Submitted via Sanity Check"
  },
  {
    "id": 36,
    "created_at": "2026-09-30",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2021,
    "driver_age": 24,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 0,
    "provider_name": "Belairdirect",
    "monthly_premium": 275,
    "coverage_type": "Full",
    "comment": "Test submission from INS-27 modal"
  },
  {
    "id": 37,
    "created_at": "2026-09-30",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Toyota",
    "vehicle_model": "RAV4",
    "vehicle_year": 2023,
    "driver_age": 45,
    "driver_profile": "experienced",
    "years_licensed": 20,
    "clean_record": 1,
    "provider_name": "TD Insurance",
    "monthly_premium": 220,
    "coverage_type": "Standard",
    "comment": "Submitted via Sanity Check"
  },
  {
    "id": 38,
    "created_at": "2026-09-30",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2021,
    "driver_age": 24,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 0,
    "provider_name": "Belairdirect",
    "monthly_premium": 275,
    "coverage_type": "Full",
    "comment": "Test submission from INS-27 modal"
  },
  {
    "id": 39,
    "created_at": "2026-09-30",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Toyota",
    "vehicle_model": "RAV4",
    "vehicle_year": 2023,
    "driver_age": 45,
    "driver_profile": "experienced",
    "years_licensed": 20,
    "clean_record": 1,
    "provider_name": "TD Insurance",
    "monthly_premium": 220,
    "coverage_type": "Standard",
    "comment": "Submitted via Sanity Check"
  },
  {
    "id": 40,
    "created_at": "2026-09-30",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2021,
    "driver_age": 24,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 0,
    "provider_name": "Belairdirect",
    "monthly_premium": 275,
    "coverage_type": "Full",
    "comment": "Test submission from INS-27 modal"
  },
  {
    "id": 41,
    "created_at": "2026-09-30",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Toyota",
    "vehicle_model": "RAV4",
    "vehicle_year": 2023,
    "driver_age": 45,
    "driver_profile": "experienced",
    "years_licensed": 20,
    "clean_record": 1,
    "provider_name": "TD Insurance",
    "monthly_premium": 220,
    "coverage_type": "Standard",
    "comment": "Submitted via Sanity Check"
  },
  {
    "id": 42,
    "created_at": "2026-09-30",
    "fsa": "M5V",
    "city": "Toronto (Downtown)",
    "vehicle_make": "Honda",
    "vehicle_model": "Civic",
    "vehicle_year": 2021,
    "driver_age": 24,
    "driver_profile": "young",
    "years_licensed": 3,
    "clean_record": 0,
    "provider_name": "Belairdirect",
    "monthly_premium": 275,
    "coverage_type": "Full",
    "comment": "Test submission from INS-27 modal"
  },
  {
    "id": 43,
    "created_at": "2026-09-30",
    "fsa": "L6P",
    "city": "Brampton",
    "vehicle_make": "Toyota",
    "vehicle_model": "RAV4",
    "vehicle_year": 2023,
    "driver_age": 45,
    "driver_profile": "experienced",
    "years_licensed": 20,
    "clean_record": 1,
    "provider_name": "TD Insurance",
    "monthly_premium": 220,
    "coverage_type": "Standard",
    "comment": "Submitted via Sanity Check"
  }
];

export const initialReviews = [
  {
    "id": 8,
    "insurer_id": "belairdirect",
    "created_at": "2026-08-10",
    "rating": 4.5,
    "title": "Great app, but renewal went up $35 for no reason",
    "body": "Signing up was super painless. Everything on the mobile app. But after 12 months with zero tickets or accidents, renewal notice arrived with a $35/mo hike. Had to call and negotiate down to $15.",
    "had_accident": 0,
    "claims_experience": "N/A",
    "payout_speed": "N/A",
    "author_city": "Markham",
    "vehicle": "2021 Toyota RAV4",
    "monthly_premium": 195,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 9,
    "insurer_id": "intact",
    "created_at": "2026-07-22",
    "rating": 5,
    "title": "Not-at-fault collision handled in 3 days",
    "body": "Someone backed into my passenger door in a plaza parking lot. Intact assigned an adjuster within 4 hours, authorized a rental via Enterprise immediately, and car was fixed at certified shop in 6 days. Worth the slightly higher premium.",
    "had_accident": 1,
    "claims_experience": "Prompt adjuster, rental car booked seamlessly, zero deductible hassle",
    "payout_speed": "3 days",
    "author_city": "Mississauga",
    "vehicle": "2022 Honda Civic",
    "monthly_premium": 260,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 10,
    "insurer_id": "caa",
    "created_at": "2026-09-01",
    "rating": 5,
    "title": "CAA MyPace is the ultimate hack if you work from home",
    "body": "I drive under 8,000 km per year because of remote work. I was paying $210 with TD, switched to CAA MyPace and now pay around $115/month based on actual mileage. Absolutely unbeatable.",
    "had_accident": 0,
    "claims_experience": "N/A",
    "payout_speed": "N/A",
    "author_city": "Toronto (Midtown)",
    "vehicle": "2019 Subaru Outback",
    "monthly_premium": 115,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 11,
    "insurer_id": "td",
    "created_at": "2026-06-18",
    "rating": 3,
    "title": "Good initial rate, but getting through to claims is a nightmare",
    "body": "Cheap rates if you graduated from UofT or Ryerson. But when windshield caught a rock on the 401, I was on hold for 85 minutes to file a glass claim. If you value customer service over price, look elsewhere.",
    "had_accident": 1,
    "claims_experience": "Long hold times, bureaucratic paperwork for glass replacement",
    "payout_speed": "14 days",
    "author_city": "Toronto (Downtown)",
    "vehicle": "2020 Mazda CX-5",
    "monthly_premium": 175,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 12,
    "insurer_id": "sonnet",
    "created_at": "2026-08-29",
    "rating": 3.5,
    "title": "100% digital quote was fast, but year 2 shock was real",
    "body": "Loved that I did not have to speak to a broker or sales rep. Got approved in 10 minutes online. Year 1 was $180/mo. Year 2 renewal came in at $245/mo with no changes on my record. Switched away immediately.",
    "had_accident": 0,
    "claims_experience": "N/A",
    "payout_speed": "N/A",
    "author_city": "Vaughan",
    "vehicle": "2023 Hyundai Elantra",
    "monthly_premium": 180,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 13,
    "insurer_id": "desjardins",
    "created_at": "2026-07-05",
    "rating": 4.5,
    "title": "Ajusto discount knocked off 18%",
    "body": "The Ajusto app is sensitive if you brake hard for yellow lights, but overall after 100 days my discount settled at 18%. Customer service reps are very polite and clear.",
    "had_accident": 0,
    "claims_experience": "N/A",
    "payout_speed": "N/A",
    "author_city": "Ottawa",
    "vehicle": "2021 Toyota Corolla",
    "monthly_premium": 140,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 14,
    "insurer_id": "intact",
    "created_at": "2026-08-14",
    "rating": 4,
    "title": "Brampton postal code hurts, but service is solid",
    "body": "L6Y postal code means you pay high regardless. Broker got me with Intact. Had an animal strike on country road, claim processed without any argument.",
    "had_accident": 1,
    "claims_experience": "Fair valuation, direct payment to body shop",
    "payout_speed": "5 days",
    "author_city": "Brampton",
    "vehicle": "2022 Ford F-150",
    "monthly_premium": 345,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 15,
    "insurer_id": "caa",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4.8,
    "title": "Best rate for low-mileage commuter",
    "body": "Switched to CAA MyPace because I work from home 3 days a week. Saved over $70/month compared to my previous policy. Renewal rate stayed identical.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Oakville",
    "vehicle": "2021 Toyota RAV4",
    "monthly_premium": 148,
    "rating_value": 5,
    "rating_claims": 5,
    "rating_support": 5,
    "rating_renewal": 5,
    "rating_ease": 4
  },
  {
    "id": 16,
    "insurer_id": "caa",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4.6,
    "title": "Smooth claim after parking lot scrape",
    "body": "Someone scraped my bumper at the grocery store. Called CAA, got rental car arranged same afternoon, and vehicle was fixed in 6 business days.",
    "had_accident": 1,
    "claims_experience": "Parking lot collision, not-at-fault claim",
    "payout_speed": "6 business days",
    "author_city": "Burlington",
    "vehicle": "2020 Subaru Forester",
    "monthly_premium": 165,
    "rating_value": 5,
    "rating_claims": 4,
    "rating_support": 5,
    "rating_renewal": 5,
    "rating_ease": 4
  },
  {
    "id": 17,
    "insurer_id": "intact",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4.2,
    "title": "Pricey but incredible claims service when needed",
    "body": "Intact is not the cheapest, but when I had a highway collision during snowstorm, their adjuster handled everything without hassle. Repair centre was top tier.",
    "had_accident": 1,
    "claims_experience": "Highway winter collision on 401",
    "payout_speed": "4 business days",
    "author_city": "Toronto (North York)",
    "vehicle": "2022 Honda CR-V",
    "monthly_premium": 245,
    "rating_value": 3,
    "rating_claims": 5,
    "rating_support": 5,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 18,
    "insurer_id": "td",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 3.8,
    "title": "Good alumni discount, but renewal crept up",
    "body": "Got a good rate initially with U of T alumni discount. Online portal is very convenient. However, second year renewal went up by $22/month despite zero tickets.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Mississauga",
    "vehicle": "2019 Mazda 3",
    "monthly_premium": 215,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 3,
    "rating_renewal": 3,
    "rating_ease": 5
  },
  {
    "id": 19,
    "insurer_id": "belairdirect",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4.2,
    "title": "Fast app setup, automerit discount works well",
    "body": "Was able to get insured in literally 10 minutes on my phone. The automerit app gave me an 18% discount after 6 months of smooth driving.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Ottawa",
    "vehicle": "2023 Hyundai Elantra",
    "monthly_premium": 185,
    "rating_value": 5,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 3,
    "rating_ease": 5
  },
  {
    "id": 20,
    "insurer_id": "desjardins",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4.4,
    "title": "Great rates in Ottawa region & bilingual service",
    "body": "Customer service agents are very friendly and clear. Ajusto app tracking is fair as long as you dont brake aggressively.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Ottawa (Kanata)",
    "vehicle": "2021 Volkswagen Golf",
    "monthly_premium": 172,
    "rating_value": 4,
    "rating_claims": 5,
    "rating_support": 5,
    "rating_renewal": 4,
    "rating_ease": 4
  },
  {
    "id": 21,
    "insurer_id": "sonnet",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4,
    "title": "Super easy to buy online with zero phone calls",
    "body": "Loved not having to talk to any sales reps. Everything in PDF right away. Changing deductible was 2 clicks.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Kitchener",
    "vehicle": "2018 Honda Civic",
    "monthly_premium": 205,
    "rating_value": 4,
    "rating_claims": 4,
    "rating_support": 4,
    "rating_renewal": 3,
    "rating_ease": 5
  },
  {
    "id": 22,
    "insurer_id": "cooperators",
    "created_at": "2026-09-21T06:48:37.863Z",
    "rating": 4.6,
    "title": "Local agent knows our family and keeps rates fair",
    "body": "We deal with the local Guelph office. When our daughter got her G2, they gave us practical advice on keeping premiums reasonable.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Guelph",
    "vehicle": "2020 Toyota Highlander",
    "monthly_premium": 228,
    "rating_value": 4,
    "rating_claims": 5,
    "rating_support": 5,
    "rating_renewal": 5,
    "rating_ease": 4
  },
  {
    "id": 23,
    "insurer_id": "squareone",
    "created_at": "2026-09-21T20:25:12.350Z",
    "rating": 4.6,
    "title": "Completely customized online quote in 5 minutes",
    "body": "Love being able to pick individual coverages and deductibles myself without pushy phone agents. Saved around $40/mo compared to my old renewal bill.",
    "had_accident": 0,
    "claims_experience": null,
    "payout_speed": null,
    "author_city": "Toronto (North York)",
    "vehicle": "2023 Hyundai Elantra",
    "monthly_premium": 185,
    "rating_value": 5,
    "rating_claims": 4,
    "rating_support": 5,
    "rating_renewal": 4,
    "rating_ease": 5
  }
];

export const initialFeedback = [
  {
    "id": 1,
    "created_at": "2026-09-23T21:29:16.656Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 2,
    "created_at": "2026-09-23T21:29:24.318Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 3,
    "created_at": "2026-09-23T21:29:31.641Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 4,
    "created_at": "2026-09-23T21:29:44.899Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 5,
    "created_at": "2026-09-23T21:31:24.702Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 6,
    "created_at": "2026-09-24T20:00:13.185Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 7,
    "created_at": "2026-09-29T05:25:38.859Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 8,
    "created_at": "2026-09-29T05:40:12.305Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 9,
    "created_at": "2026-09-30T10:57:37.849Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 10,
    "created_at": "2026-09-30T11:55:19.801Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 11,
    "created_at": "2026-09-30T11:59:23.537Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 12,
    "created_at": "2026-09-30T12:00:09.820Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 13,
    "created_at": "2026-09-30T12:00:45.502Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  },
  {
    "id": 14,
    "created_at": "2026-09-30T22:36:47.005Z",
    "rating": 5,
    "is_reasonable": "Yes",
    "matches_knowledge": "Yes",
    "use_before_renew": "Yes",
    "use_before_buy": "Yes",
    "trust_comment": "Great baseline, matched my Intact renewal quote.",
    "postal_code": "M4N",
    "vehicle": "2022 Honda Civic",
    "benchmark_rate": 215,
    "current_premium": 220
  }
];

export const initialLeads = [
  {
    "id": 1,
    "created_at": "2026-09-14T21:25:40.710Z",
    "name": "Dmitry Klimenkov",
    "email": "dmitry@example.com",
    "phone": "416-555-0199",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 560,
    "estimated_savings": 1932,
    "status": "new"
  },
  {
    "id": 2,
    "created_at": "2026-09-23T21:29:16.659Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 3,
    "created_at": "2026-09-23T21:29:16.678Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 4,
    "created_at": "2026-09-23T21:29:24.321Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 5,
    "created_at": "2026-09-23T21:29:24.339Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 6,
    "created_at": "2026-09-23T21:29:31.644Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 7,
    "created_at": "2026-09-23T21:29:31.663Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 8,
    "created_at": "2026-09-23T21:29:44.901Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 9,
    "created_at": "2026-09-23T21:29:44.919Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 10,
    "created_at": "2026-09-23T21:31:24.704Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 11,
    "created_at": "2026-09-23T21:31:24.723Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 12,
    "created_at": "2026-09-24T20:00:13.188Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 13,
    "created_at": "2026-09-24T20:00:13.208Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 14,
    "created_at": "2026-09-29T05:25:38.898Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 15,
    "created_at": "2026-09-29T05:25:38.955Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 16,
    "created_at": "2026-09-29T05:40:12.309Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 17,
    "created_at": "2026-09-29T05:40:12.328Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 18,
    "created_at": "2026-09-30T10:57:37.852Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 19,
    "created_at": "2026-09-30T10:57:37.869Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 20,
    "created_at": "2026-09-30T11:55:19.804Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 21,
    "created_at": "2026-09-30T11:55:19.822Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 22,
    "created_at": "2026-09-30T11:59:23.539Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 23,
    "created_at": "2026-09-30T11:59:23.555Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 24,
    "created_at": "2026-09-30T12:00:09.822Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 25,
    "created_at": "2026-09-30T12:00:09.840Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 26,
    "created_at": "2026-09-30T12:00:45.504Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 27,
    "created_at": "2026-09-30T12:00:45.522Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  },
  {
    "id": 28,
    "created_at": "2026-09-30T22:36:47.008Z",
    "name": "John Tester",
    "email": "john@test.ca",
    "phone": "4165551234",
    "vehicle": "2022 Honda CR-V",
    "postal_code": "L6P",
    "current_premium": 320,
    "estimated_savings": 600,
    "status": "contacted"
  },
  {
    "id": 29,
    "created_at": "2026-09-30T22:36:47.027Z",
    "name": "Savings Locker",
    "email": "locker@test.ca",
    "phone": "4165559999",
    "vehicle": "2023 Toyota RAV4",
    "postal_code": "M4N",
    "current_premium": 300,
    "estimated_savings": 450,
    "status": "new"
  }
];

export const initialStats = {
  "total_money_saved": 6300,
  "total_checks_run": 32,
  "avg_monthly_overpay": 0
};
