import { db } from './db.js';

export function ensureInsurersPopulated() {
  const insurers = [
    {
      id: 'intact',
      name: 'Intact Insurance',
      logo_color: '#e31b23',
      avg_monthly: 245,
      rating_value: 3.8,
      rating_claims: 4.6,
      rating_support: 4.4,
      rating_renewal: 3.7,
      rating_ease: 4.3,
      overall_rating: 4.2,
      total_reviews: 74,
      pros: 'Largest provider network in Canada, top-tier claims speed and reliable network of approved collision repair centres.',
      cons: 'Higher baseline rates than direct-only discount carriers; policies must be managed through independent brokers.',
      direct_online: 0,
      broker_only: 1,
      website: 'https://www.intact.ca'
    },
    {
      id: 'td',
      name: 'TD Insurance',
      logo_color: '#008a00',
      avg_monthly: 228,
      rating_value: 4.1,
      rating_claims: 3.9,
      rating_support: 3.7,
      rating_renewal: 3.4,
      rating_ease: 4.2,
      overall_rating: 3.9,
      total_reviews: 86,
      pros: 'Deep university alumni, professional association, and TD banking bundle discounts.',
      cons: 'Customer support wait times peak in fall/winter; strict automated rate increases on annual renewal.',
      direct_online: 1,
      broker_only: 0,
      website: 'https://www.tdinsurance.com'
    },
    {
      id: 'aviva',
      name: 'Aviva Canada',
      logo_color: '#f59e0b',
      avg_monthly: 240,
      rating_value: 3.9,
      rating_claims: 4.2,
      rating_support: 4.0,
      rating_renewal: 3.6,
      rating_ease: 4.1,
      overall_rating: 4.0,
      total_reviews: 58,
      pros: 'Comprehensive rideshare (Lyft/Uber) coverage endorsements, broad broker availability across Ontario.',
      cons: 'Substantial renewal rate jumps in GTA high-claim postal codes (Brampton, Vaughan); changes require broker assistance.',
      direct_online: 0,
      broker_only: 1,
      website: 'https://www.aviva.ca'
    },
    {
      id: 'belairdirect',
      name: 'Belairdirect',
      logo_color: '#005691',
      avg_monthly: 215,
      rating_value: 4.4,
      rating_claims: 4.1,
      rating_support: 4.2,
      rating_renewal: 3.5,
      rating_ease: 4.5,
      overall_rating: 4.1,
      total_reviews: 67,
      pros: 'Modern mobile app, quick online quotes in 3 minutes, automerit telematics discount up to 25%.',
      cons: 'Introductory promotional discounts often taper off upon year-1 renewal; phone lines get busy.',
      direct_online: 1,
      broker_only: 0,
      website: 'https://www.belairdirect.com'
    },
    {
      id: 'caa',
      name: 'CAA Insurance',
      logo_color: '#002f6c',
      avg_monthly: 198,
      rating_value: 4.7,
      rating_claims: 4.7,
      rating_support: 4.8,
      rating_renewal: 4.6,
      rating_ease: 4.5,
      overall_rating: 4.7,
      total_reviews: 82,
      pros: 'CAA MyPace pay-as-you-drive for low-mileage drivers, additional 15-20% membership discount, consistent rates.',
      cons: 'Pay-per-km requires OBD device tracking, conservative quoting for brand-new novice drivers.',
      direct_online: 1,
      broker_only: 0,
      website: 'https://www.caainsurance.ca'
    },
    {
      id: 'economical',
      name: 'Economical Insurance',
      logo_color: '#0284c7',
      avg_monthly: 235,
      rating_value: 4.0,
      rating_claims: 4.3,
      rating_support: 4.1,
      rating_renewal: 3.8,
      rating_ease: 4.0,
      overall_rating: 4.0,
      total_reviews: 42,
      pros: 'Part of Definity Financial Group; strong personal vehicle lines with reliable claims adjusters.',
      cons: 'Distributed through independent broker channel rather than a direct online purchase portal.',
      direct_online: 0,
      broker_only: 1,
      website: 'https://www.economical.com'
    },
    {
      id: 'desjardins',
      name: 'Desjardins Insurance',
      logo_color: '#00874e',
      avg_monthly: 232,
      rating_value: 4.1,
      rating_claims: 4.3,
      rating_support: 4.3,
      rating_renewal: 3.8,
      rating_ease: 4.2,
      overall_rating: 4.1,
      total_reviews: 55,
      pros: 'Ajusto app telematics discount, excellent bilingual English/French support, very competitive in Ottawa and Eastern Ontario.',
      cons: 'Ajusto app scoring can be sensitive to sudden braking and late-night commuting.',
      direct_online: 1,
      broker_only: 0,
      website: 'https://www.desjardinsgeneralinsurance.com'
    },
    {
      id: 'cooperators',
      name: 'Co-operators',
      logo_color: '#ea580c',
      avg_monthly: 238,
      rating_value: 4.2,
      rating_claims: 4.5,
      rating_support: 4.6,
      rating_renewal: 4.2,
      rating_ease: 4.3,
      overall_rating: 4.4,
      total_reviews: 51,
      pros: 'High customer loyalty, dedicated local financial advisor offices across Ontario, fair claims settlement ethos.',
      cons: 'Slightly higher standalone auto premiums without home/commercial policy bundling.',
      direct_online: 1,
      broker_only: 0,
      website: 'https://www.cooperators.ca'
    },
    {
      id: 'sonnet',
      name: 'Sonnet Insurance',
      logo_color: '#475569',
      avg_monthly: 220,
      rating_value: 4.3,
      rating_claims: 3.8,
      rating_support: 4.0,
      rating_renewal: 3.6,
      rating_ease: 4.6,
      overall_rating: 4.1,
      total_reviews: 49,
      pros: '100% digital self-serve experience; instant online quote and binding without speaking to an agent.',
      cons: 'Digital-first support can make resolving nuanced collision liability disputes slower.',
      direct_online: 1,
      broker_only: 0,
      website: 'https://www.sonnet.ca'
    },
    {
      id: 'squareone',
      name: 'Square One Insurance',
      logo_color: '#005596',
      avg_monthly: 195,
      rating_value: 4.5,
      rating_claims: 4.3,
      rating_support: 4.6,
      rating_renewal: 4.2,
      rating_ease: 4.8,
      overall_rating: 4.5,
      total_reviews: 42,
      pros: '100% online customizable coverage, transparent digital policy management, no broker fees, high customer satisfaction.',
      cons: 'Auto coverage in Ontario is newer compared to their home insurance; underwriting restrictions on some commercial or specialty vehicles.',
      direct_online: 1,
      broker_only: 0,
      website: 'https://www.squareone.ca'
    },
    {
      id: 'wawanesa',
      name: 'Wawanesa Insurance',
      logo_color: '#0369a1',
      avg_monthly: 225,
      rating_value: 4.5,
      rating_claims: 4.4,
      rating_support: 4.3,
      rating_renewal: 4.1,
      rating_ease: 4.0,
      overall_rating: 4.3,
      total_reviews: 47,
      pros: 'Consistently competitive baseline rates for clean-record drivers and families; mutual insurer model.',
      cons: 'Sold strictly via insurance brokers; online customer portal has fewer self-service features.',
      direct_online: 0,
      broker_only: 1,
      website: 'https://www.wawanesa.com'
    },
    {
      id: 'travelers',
      name: 'Travelers Canada',
      logo_color: '#dc2626',
      avg_monthly: 242,
      rating_value: 3.9,
      rating_claims: 4.3,
      rating_support: 4.1,
      rating_renewal: 3.9,
      rating_ease: 4.1,
      overall_rating: 4.1,
      total_reviews: 38,
      pros: 'IntelliDrive telematics discount, attractive bundle packages for multi-car homeowners.',
      cons: 'Less competitive pricing for novice G2 drivers under 25.',
      direct_online: 0,
      broker_only: 1,
      website: 'https://www.travelerscanada.ca'
    },
    {
      id: 'allstate',
      name: 'Allstate Insurance',
      logo_color: '#1d4ed8',
      avg_monthly: 236,
      rating_value: 4.0,
      rating_claims: 4.1,
      rating_support: 4.2,
      rating_renewal: 3.7,
      rating_ease: 4.2,
      overall_rating: 4.0,
      total_reviews: 44,
      pros: 'Drivewise telematics up to 30% discount, Claim Forgiveness endorsement, local physical agencies.',
      cons: 'Renewal rates frequently jump after first-year discount expires.',
      direct_online: 1,
      broker_only: 0,
      website: 'https://www.allstate.ca'
    },
    {
      id: 'goremutual',
      name: 'Gore Mutual',
      logo_color: '#7e22ce',
      avg_monthly: 230,
      rating_value: 4.1,
      rating_claims: 4.2,
      rating_support: 4.3,
      rating_renewal: 4.0,
      rating_ease: 3.9,
      overall_rating: 4.1,
      total_reviews: 31,
      pros: 'Canada’s oldest property & casualty mutual; personalized claims handling and community focus.',
      cons: 'Smaller brand recognition and digital app presence compared to national giants.',
      direct_online: 0,
      broker_only: 1,
      website: 'https://www.goremutual.ca'
    },
    {
      id: 'northbridge',
      name: 'Northbridge Insurance',
      logo_color: '#1e3a8a',
      avg_monthly: 255,
      rating_value: 3.8,
      rating_claims: 4.5,
      rating_support: 4.3,
      rating_renewal: 3.9,
      rating_ease: 4.1,
      overall_rating: 4.1,
      total_reviews: 29,
      pros: 'Specialized in commercial vehicles, fleets, tradespeople and high-value vehicle policies.',
      cons: 'Seldom the most cost-effective for single personal daily drivers.',
      direct_online: 0,
      broker_only: 1,
      website: 'https://www.nbins.com'
    },
    {
      id: 'facility',
      name: 'Facility Association',
      logo_color: '#64748b',
      avg_monthly: 680,
      rating_value: 2.5,
      rating_claims: 3.7,
      rating_support: 3.4,
      rating_renewal: 3.0,
      rating_ease: 3.2,
      overall_rating: 3.2,
      total_reviews: 24,
      pros: 'Ontario insurer of last resort; legally guarantees coverage for high-risk drivers turned down by standard carriers.',
      cons: 'Mandatory high surcharges; expensive premiums designed as a temporary solution until driver record clears.',
      direct_online: 0,
      broker_only: 1,
      website: 'https://www.facilityassociation.com'
    }
  ];

  const upsertInsurer = db.prepare(`
    INSERT INTO insurers (
      id, name, logo_color, avg_monthly, claims_rating, support_rating, price_rating,
      rating_value, rating_claims, rating_support, rating_renewal, rating_ease, overall_rating,
      total_reviews, pros, cons, direct_online, broker_only, website
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(id) DO UPDATE SET
      name=excluded.name,
      logo_color=excluded.logo_color,
      avg_monthly=excluded.avg_monthly,
      claims_rating=excluded.claims_rating,
      support_rating=excluded.support_rating,
      price_rating=excluded.price_rating,
      rating_value=excluded.rating_value,
      rating_claims=excluded.rating_claims,
      rating_support=excluded.rating_support,
      rating_renewal=excluded.rating_renewal,
      rating_ease=excluded.rating_ease,
      overall_rating=excluded.overall_rating,
      total_reviews=excluded.total_reviews,
      pros=excluded.pros,
      cons=excluded.cons,
      direct_online=excluded.direct_online,
      broker_only=excluded.broker_only,
      website=excluded.website;
  `);

  for (const ins of insurers) {
    upsertInsurer.run(
      ins.id,
      ins.name,
      ins.logo_color,
      ins.avg_monthly,
      ins.rating_claims, // claims_rating legacy
      ins.rating_support, // support_rating legacy
      ins.rating_value, // price_rating legacy
      ins.rating_value,
      ins.rating_claims,
      ins.rating_support,
      ins.rating_renewal,
      ins.rating_ease,
      ins.overall_rating,
      ins.total_reviews,
      ins.pros,
      ins.cons,
      ins.direct_online,
      ins.broker_only,
      ins.website
    );
  }

  // Seed sample reviews for insurers that have no reviews
  const insertReview = db.prepare(`
    INSERT INTO reviews (
      insurer_id, created_at, rating, rating_value, rating_claims, rating_support, rating_renewal, rating_ease,
      title, body, had_accident, claims_experience, payout_speed, author_city, vehicle, monthly_premium
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

    const sampleReviews = [
      {
        insurer_id: 'caa',
        rating: 4.8,
        rating_value: 5,
        rating_claims: 5,
        rating_support: 5,
        rating_renewal: 5,
        rating_ease: 4,
        title: 'Best rate for low-mileage commuter',
        body: 'Switched to CAA MyPace because I work from home 3 days a week. Saved over $70/month compared to my previous policy. Renewal rate stayed identical.',
        had_accident: 0,
        claims_experience: null,
        payout_speed: null,
        author_city: 'Oakville',
        vehicle: '2021 Toyota RAV4',
        monthly_premium: 148
      },
      {
        insurer_id: 'caa',
        rating: 4.6,
        rating_value: 5,
        rating_claims: 4,
        rating_support: 5,
        rating_renewal: 5,
        rating_ease: 4,
        title: 'Smooth claim after parking lot scrape',
        body: 'Someone scraped my bumper at the grocery store. Called CAA, got rental car arranged same afternoon, and vehicle was fixed in 6 business days.',
        had_accident: 1,
        claims_experience: 'Parking lot collision, not-at-fault claim',
        payout_speed: '6 business days',
        author_city: 'Burlington',
        vehicle: '2020 Subaru Forester',
        monthly_premium: 165
      },
      {
        insurer_id: 'intact',
        rating: 4.2,
        rating_value: 3,
        rating_claims: 5,
        rating_support: 5,
        rating_renewal: 4,
        rating_ease: 4,
        title: 'Pricey but incredible claims service when needed',
        body: 'Intact is not the cheapest, but when I had a highway collision during snowstorm, their adjuster handled everything without hassle. Repair centre was top tier.',
        had_accident: 1,
        claims_experience: 'Highway winter collision on 401',
        payout_speed: '4 business days',
        author_city: 'Toronto (North York)',
        vehicle: '2022 Honda CR-V',
        monthly_premium: 245
      },
      {
        insurer_id: 'td',
        rating: 3.8,
        rating_value: 4,
        rating_claims: 4,
        rating_support: 3,
        rating_renewal: 3,
        rating_ease: 5,
        title: 'Good alumni discount, but renewal crept up',
        body: 'Got a good rate initially with U of T alumni discount. Online portal is very convenient. However, second year renewal went up by $22/month despite zero tickets.',
        had_accident: 0,
        claims_experience: null,
        payout_speed: null,
        author_city: 'Mississauga',
        vehicle: '2019 Mazda 3',
        monthly_premium: 215
      },
      {
        insurer_id: 'belairdirect',
        rating: 4.2,
        rating_value: 5,
        rating_claims: 4,
        rating_support: 4,
        rating_renewal: 3,
        rating_ease: 5,
        title: 'Fast app setup, automerit discount works well',
        body: 'Was able to get insured in literally 10 minutes on my phone. The automerit app gave me an 18% discount after 6 months of smooth driving.',
        had_accident: 0,
        claims_experience: null,
        payout_speed: null,
        author_city: 'Ottawa',
        vehicle: '2023 Hyundai Elantra',
        monthly_premium: 185
      },
      {
        insurer_id: 'desjardins',
        rating: 4.4,
        rating_value: 4,
        rating_claims: 5,
        rating_support: 5,
        rating_renewal: 4,
        rating_ease: 4,
        title: 'Great rates in Ottawa region & bilingual service',
        body: 'Customer service agents are very friendly and clear. Ajusto app tracking is fair as long as you dont brake aggressively.',
        had_accident: 0,
        claims_experience: null,
        payout_speed: null,
        author_city: 'Ottawa (Kanata)',
        vehicle: '2021 Volkswagen Golf',
        monthly_premium: 172
      },
      {
        insurer_id: 'sonnet',
        rating: 4.0,
        rating_value: 4,
        rating_claims: 4,
        rating_support: 4,
        rating_renewal: 3,
        rating_ease: 5,
        title: 'Super easy to buy online with zero phone calls',
        body: 'Loved not having to talk to any sales reps. Everything in PDF right away. Changing deductible was 2 clicks.',
        had_accident: 0,
        claims_experience: null,
        payout_speed: null,
        author_city: 'Kitchener',
        vehicle: '2018 Honda Civic',
        monthly_premium: 205
      },
      {
        insurer_id: 'cooperators',
        rating: 4.6,
        rating_value: 4,
        rating_claims: 5,
        rating_support: 5,
        rating_renewal: 5,
        rating_ease: 4,
        title: 'Local agent knows our family and keeps rates fair',
        body: 'We deal with the local Guelph office. When our daughter got her G2, they gave us practical advice on keeping premiums reasonable.',
        had_accident: 0,
        claims_experience: null,
        payout_speed: null,
        author_city: 'Guelph',
        vehicle: '2020 Toyota Highlander',
        monthly_premium: 228
      },
      {
        insurer_id: 'squareone',
        rating: 4.6,
        rating_value: 5,
        rating_claims: 4,
        rating_support: 5,
        rating_renewal: 4,
        rating_ease: 5,
        title: 'Completely customized online quote in 5 minutes',
        body: 'Love being able to pick individual coverages and deductibles myself without pushy phone agents. Saved around $40/mo compared to my old renewal bill.',
        had_accident: 0,
        claims_experience: null,
        payout_speed: null,
        author_city: 'Toronto (North York)',
        vehicle: '2023 Hyundai Elantra',
        monthly_premium: 185
      }
    ];

  const today = new Date().toISOString();
  for (const rev of sampleReviews) {
    const existing = db.prepare('SELECT id FROM reviews WHERE insurer_id = ?').get(rev.insurer_id);
    if (!existing) {
      insertReview.run(
        rev.insurer_id,
        today,
        rev.rating,
        rev.rating_value,
        rev.rating_claims,
        rev.rating_support,
        rev.rating_renewal,
        rev.rating_ease,
        rev.title,
        rev.body,
        rev.had_accident,
        rev.claims_experience,
        rev.payout_speed,
        rev.author_city,
        rev.vehicle,
        rev.monthly_premium
      );
    }
  }

  console.log('16 Ontario insurers populated with 5-dimension rating metrics.');
}
