import React from 'react';
import { ArrowLeft, FileText } from 'lucide-react';

export function TermsOfUse({ onBack }) {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-10 space-y-6">
      {onBack && (
        <button
          type="button"
          onClick={onBack}
          className="inline-flex items-center gap-2 text-xs font-bold text-slate-400 hover:text-emerald-400 transition cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Rate Checker</span>
        </button>
      )}

      <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 sm:p-10 backdrop-blur-xl shadow-2xl text-slate-300 space-y-8 text-sm leading-relaxed">
        {/* Header */}
        <div className="border-b border-slate-800 pb-6">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/15 text-emerald-400 flex items-center justify-center shrink-0">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h1 className="text-2xl sm:text-3xl font-black text-white">Terms of Use</h1>
              <p className="text-xs text-slate-400 mt-0.5">Last updated: September 23, 2026</p>
            </div>
          </div>
          <p className="mt-4 text-slate-300">
            Welcome to InsurCheck. These Terms of Use ("Terms") govern your use of the InsurCheck website, calculators, estimates, benchmarks, reviews, and other services available through our website (collectively, the "Service").
          </p>
          <p className="mt-2 text-slate-400">
            By using the Service, you agree to these Terms. If you do not agree with these Terms, please do not use the Service.
          </p>
        </div>

        {/* Section 1 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">1.</span> About InsurCheck
          </h2>
          <p>
            InsurCheck is an independent information and comparison platform designed to help Ontario drivers better understand automobile insurance pricing.
          </p>
          <p className="p-3 bg-slate-950/70 border border-slate-800 rounded-xl text-slate-300 font-medium">
            InsurCheck is <strong className="text-white">not an insurance company, insurance broker, insurer, or financial advisor</strong>. We are not affiliated with FSRA, the Government of Ontario, or any insurance provider unless explicitly stated.
          </p>
        </section>

        {/* Section 2 */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">2.</span> Insurance Estimates Are Not Quotes
          </h2>
          <p>
            Any insurance price, benchmark, estimate, range, savings amount, or other pricing information displayed by InsurCheck is provided for <strong className="text-white">informational purposes only</strong>.
          </p>
          <p>
            A result generated by our calculator is not an insurance quote, offer of insurance, contract, or guarantee of the price you will receive from an insurer or broker.
          </p>
          <p>Actual insurance premiums can vary based on many factors, including:</p>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs text-slate-300 bg-slate-950/40 p-4 rounded-xl border border-slate-850">
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0"></span>
              <span>Driver age and experience</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0"></span>
              <span>Driving and insurance history</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0"></span>
              <span>Claims, tickets, and convictions</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0"></span>
              <span>Vehicle make, model, year, and use</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0"></span>
              <span>Location</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0"></span>
              <span>Coverage and deductibles</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0"></span>
              <span>Annual mileage</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0"></span>
              <span>Discounts and eligibility</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0"></span>
              <span>Underwriting criteria</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0"></span>
              <span>Insurer-specific pricing and rules</span>
            </li>
            <li className="flex items-center gap-2 sm:col-span-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0"></span>
              <span>Other information requested by an insurer or broker</span>
            </li>
          </ul>
          <p className="text-xs text-slate-400">
            The information used to calculate an estimate may not include every factor considered by an insurer.
          </p>
          <div className="p-3 bg-amber-500/10 border border-amber-500/30 rounded-xl text-amber-200 font-semibold text-xs sm:text-sm">
            You should obtain an official quote from a licensed Ontario insurance provider or broker before making an insurance decision.
          </div>
        </section>

        {/* Section 3 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">3.</span> Fair Market Estimates and Benchmarks
          </h2>
          <p>
            InsurCheck may provide an estimated "fair market" price or benchmark based on information provided by users, publicly available information, insurer pricing information, and other data sources.
          </p>
          <p>
            These benchmarks are estimates and may change as additional information becomes available. A benchmark does not mean that a particular insurer will offer the displayed price.
          </p>
          <p>
            Where we display potential savings, the amount represents an <strong className="text-white">estimated potential difference</strong> between the information provided by the user and our calculated benchmark. It is not a guaranteed saving.
          </p>
        </section>

        {/* Section 4 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">4.</span> Insurance Provider Information
          </h2>
          <p>
            InsurCheck may display information about insurance companies, brokers, products, prices, reviews, or other insurance-related services.
          </p>
          <p>
            The appearance of an insurer, broker, or other provider on InsurCheck does not constitute an endorsement or recommendation.
          </p>
          <p>
            Information about third parties may change without notice. Users should verify current pricing, coverage, eligibility, terms, and availability directly with the relevant provider.
          </p>
        </section>

        {/* Section 5 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">5.</span> Broker and Quote Referrals
          </h2>
          <p>
            Where available, InsurCheck may provide an option to connect users with licensed insurance brokers or other insurance providers.
          </p>
          <p>
            Submitting your information does not guarantee that you will receive a quote, a particular price, coverage, or an offer of insurance.
          </p>
          <p>
            Any insurance policy or quote obtained through a third-party broker or insurer is subject to that provider's own terms, underwriting requirements, and privacy policies.
          </p>
        </section>

        {/* Section 6 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">6.</span> Community Data and User Submissions
          </h2>
          <p>
            InsurCheck may allow users to voluntarily submit information such as insurance premiums, vehicle information, locations, experiences, and reviews.
          </p>
          <p>
            Information submitted for community benchmarking may be aggregated, anonymized, or otherwise processed for purposes including:
          </p>
          <ul className="list-disc list-inside space-y-1 text-xs text-slate-300 pl-2">
            <li>Improving our estimates and benchmarks</li>
            <li>Developing market insights</li>
            <li>Improving the Service</li>
            <li>Publishing aggregated insurance pricing information</li>
            <li>Understanding insurance pricing trends</li>
          </ul>
          <p className="text-xs text-slate-400">
            Users should not submit sensitive personal information or information belonging to another person without authorization. We may remove, modify, or exclude submissions that we believe are inaccurate, misleading, duplicated, fraudulent, inappropriate, or otherwise unsuitable for use on the Service.
          </p>
        </section>

        {/* Section 7 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">7.</span> Reviews and User-Generated Content
          </h2>
          <p>
            Users may submit reviews, comments, ratings, or other content about insurance providers.
          </p>
          <p>
            User-generated content represents the views of the person who submitted it and does not necessarily represent the views of InsurCheck. We do not guarantee that all user-submitted information or reviews are accurate, complete, or independently verified.
          </p>
          <p>
            By submitting content, you confirm that you have the right to submit it and that it does not knowingly contain false, unlawful, defamatory, or infringing material.
          </p>
          <p>
            You grant InsurCheck a non-exclusive, worldwide, royalty-free right to use, reproduce, modify, aggregate, and display your submitted content for operating, improving, and promoting the Service.
          </p>
        </section>

        {/* Section 8 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">8.</span> Accuracy of Information
          </h2>
          <p>
            We make reasonable efforts to provide useful and accurate information, but we do not guarantee that information on the Service is:
          </p>
          <ul className="list-disc list-inside space-y-1 text-xs text-slate-300 pl-2">
            <li>Accurate</li>
            <li>Complete</li>
            <li>Current</li>
            <li>Error-free</li>
            <li>Suitable for your particular situation</li>
          </ul>
          <p>
            Insurance pricing and regulations can change. Information displayed on the Service may therefore become outdated. You are responsible for verifying important information before making an insurance, financial, or vehicle purchase decision.
          </p>
        </section>

        {/* Section 9 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">9.</span> No Financial or Insurance Advice
          </h2>
          <p>
            Information provided through InsurCheck is general information and should not be considered insurance, financial, legal, or professional advice.
          </p>
          <p>
            Your individual insurance needs depend on your circumstances. You should consult a licensed insurance professional for advice about your specific coverage needs.
          </p>
        </section>

        {/* Section 10 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">10.</span> Third-Party Services and Links
          </h2>
          <p>
            The Service may contain links, integrations, advertisements, or other connections to third-party websites and services.
          </p>
          <p>
            InsurCheck does not control and is not responsible for third-party websites, services, products, pricing, content, privacy practices, or availability. Your use of a third-party service is subject to that third party's own terms and policies.
          </p>
        </section>

        {/* Section 11 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">11.</span> Availability of the Service
          </h2>
          <p>
            We may modify, suspend, or discontinue any part of the Service at any time without notice. We do not guarantee that the Service will always be available, uninterrupted, secure, or free from errors.
          </p>
        </section>

        {/* Section 12 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">12.</span> Prohibited Use
          </h2>
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-1 text-xs text-slate-300 pl-2">
            <li>Use the Service for unlawful purposes</li>
            <li>Provide knowingly false or misleading information</li>
            <li>Attempt to interfere with or disrupt the Service</li>
            <li>Attempt to gain unauthorized access to our systems or data</li>
            <li>Scrape, copy, or systematically collect Service data without our permission</li>
            <li>Use the Service to impersonate another person</li>
            <li>Upload malicious code or harmful content</li>
            <li>Use the Service in a way that could damage InsurCheck or other users</li>
          </ul>
        </section>

        {/* Section 13 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">13.</span> Intellectual Property
          </h2>
          <p>
            The InsurCheck website, including its design, branding, software, graphics, text, original calculations, and other materials, is owned by or licensed to InsurCheck unless otherwise stated.
          </p>
          <p>
            You may use the Service for personal, non-commercial purposes. You may not reproduce, distribute, modify, sell, or commercially exploit InsurCheck's proprietary content without prior written permission.
          </p>
        </section>

        {/* Section 14 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">14.</span> Privacy
          </h2>
          <p>
            Your use of the Service is also subject to our <strong className="text-white">Privacy Policy</strong>, which explains how we collect, use, disclose, and protect information. Please review our Privacy Policy before submitting personal information through the Service.
          </p>
        </section>

        {/* Section 15 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">15.</span> Disclaimer of Warranties
          </h2>
          <p>
            To the maximum extent permitted by applicable law, the Service is provided on an "as is" and "as available" basis.
          </p>
          <p>
            InsurCheck makes no warranties or representations regarding the accuracy, reliability, availability, completeness, or suitability of the Service or any information provided through it.
          </p>
          <p className="text-xs text-slate-400">
            Nothing in these Terms excludes or limits any rights or protections that cannot legally be excluded or limited under applicable law.
          </p>
        </section>

        {/* Section 16 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">16.</span> Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by applicable law, InsurCheck and its owners, operators, employees, contractors, and service providers will not be liable for any loss, damage, cost, or expense arising from or related to:
          </p>
          <ul className="list-disc list-inside space-y-1 text-xs text-slate-300 pl-2">
            <li>Your use of or reliance on the Service</li>
            <li>An insurance estimate or benchmark</li>
            <li>An insurance quote or policy obtained from a third party</li>
            <li>Errors or omissions in information displayed on the Service</li>
            <li>Third-party websites or services</li>
            <li>Interruption or unavailability of the Service</li>
          </ul>
          <p className="text-xs text-slate-400">
            Nothing in these Terms limits liability where such limitation is prohibited by law.
          </p>
        </section>

        {/* Section 17 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">17.</span> Changes to These Terms
          </h2>
          <p>
            We may update these Terms from time to time. When we make changes, we will update the "Last updated" date at the top of this page. Your continued use of the Service after changes are posted means you accept the updated Terms.
          </p>
        </section>

        {/* Section 18 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">18.</span> Governing Law
          </h2>
          <p>
            These Terms are governed by the laws of the Province of Ontario and the applicable laws of Canada. Any dispute relating to these Terms or the Service will be subject to the applicable courts of Ontario, Canada.
          </p>
        </section>

        {/* Section 19 */}
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">19.</span> Contact Us
          </h2>
          <p>
            If you have questions about these Terms or the InsurCheck Service, please contact us through the Contact Us page on our website.
          </p>
        </section>

        {/* Footer Note */}
        <div className="pt-6 border-t border-slate-800 text-xs text-slate-500">
          <p className="font-semibold text-slate-400">
            InsurCheck is an independent insurance information and benchmarking platform. We are not affiliated with FSRA, the Government of Ontario, or any insurance provider unless explicitly stated.
          </p>
        </div>
      </div>
    </div>
  );
}
